name: Pipeline update instances by SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Execute command on remote server
        env:
          INSTANCE_1_SSH_HOST: ${{ secrets.INSTANCE_1_SSH_HOST }}
          INSTANCE_1_SSH_USER: ${{ secrets.INSTANCE_1_SSH_USER }}
          INSTANCE_1_SSH_PASSWORD: ${{ secrets.INSTANCE_1_SSH_PASSWORD }}
        run: sshpass -p $INSTANCE_1_SSH_PASSWORD ssh -tt -o StrictHostKeyChecking=no -x $INSTANCE_1_SSH_USER@$INSTANCE_1_SSH_HOST sudo -S <<< $INSTANCE_1_SSH_PASSWORD < command-to-instance-1.sh # maybe has to remove this '' of ssh_password
