name: Pipeline update instances by SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Execute command on remote server
        env:
          SSH_HOST: ${{ secrets.INSTANCE_1_SSH_HOST }}
          SSH_USER: ${{ secrets.INSTANCE_1_SSH_USER }}
          SSH_PASSWORD: ${{ secrets.INSTANCE_1_SSH_PASSWORD }}
        run: sshpass -p '$SSH_PASSWORD' ssh -tt $SSH_USER@$SSH_HOST < command-to-instance-1.txt # maybe has to remove this '' of ssh_password
